server :
  port : 8091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/teguatos/ApplicationConfig.git
          searchPaths: 
          username: teguatos
          password: Tegu@molly21403.Sjn
          default-label: "main"
  security:
    user:
      name: root
      password: s3cr3t
